# Generated by Django 4.2.4 on 2023-08-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designation',
            new_name='department',
        ),
    ]
